# Generated by Django 4.2.18 on 2025-06-30 05:11

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('title_tag', models.CharField(default='Data Analysis', max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=455)),
                ('meta_keywords', models.TextField(blank=True, max_length=455)),
                ('thumbnail', models.ImageField(blank=True, upload_to='datasets/thumbnail/%Y/%m/%d/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='datasets/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
